[package]
name = "grust-issundb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "IssunDB GraphStore backend for Grust."
keywords.workspace = true
categories.workspace = true

[dependencies]
async-trait = { workspace = true }
grust-core = { version = "0.8.1", path = "../grust-core" }
issundb = { workspace = true }
rmp-serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
